language: node_js

node_js:
  - "0.10"

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#sailsjs"
    on_success: never
    on_failure: always
    template:
      - "Build by %{author} has failed:"
      - "Git Info: %{branch} - %{commit}"
      - "Travis states: %{message}"
      - "Build Details: %{build_url}"
      - "Change View: %{compare_url}"
    skip_join: true

# whitelisted branches
branches:
  only:
    - master
    - stable
    - beta